# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.customize ["modifyvm", :id, "--clipboard-mode", "bidirectional"]
  end

  config.vm.provision "default", type: "shell" do |s|
    s.powershell_elevated_interactive = true
    s.inline = %{
cd C:\\vagrant
.\\provision-performance.ps1
.\\provision-bginfo.ps1
.\\provision-timezone.ps1
.\\provision-powersettings.ps1
.\\provision-locale.ps1
.\\provision-chocolatey.ps1
.\\provision-chocolatey-packages.ps1
}
  end

  {
    "win7-ie8" => {
      "port" => 49600
    },
    "win7-ie9" => {
      "port" => 49700
    },
    "win7-ie10" => {
      "port" => 49800
    },
    "win7-ie11" => {
      "port" => 49900
    },
    "win81-ie11" => {
      "port" => 50000
    },
    "win10-edge" => {
      "port" => 50100
    }
  }.each do |name, attr|
    config.vm.define "#{name}" do |node|

      node.vm.box = "breeze/#{name}"

      node.vm.network "forwarded_port",
        id: "ssh",
        guest: 22,
        host: attr['port'] + 0,
        host_ip: "127.0.0.1",
        auto_correct: true
      node.vm.network "forwarded_port",
        id: "winrm",
        guest: 5985,
        host: attr['port'] + 1,
        host_ip: "127.0.0.1",
        auto_correct: true
      node.vm.network "forwarded_port",
        id: "winrm-ssl",
        guest: 5986,
        host: attr['port'] + 2,
        host_ip: "127.0.0.1",
        auto_correct: true
      node.vm.network "forwarded_port",
        id: "rdp",
        guest: 3389,
        host: attr['port'] + 3,
        host_ip: "127.0.0.1",
        auto_correct: true

      node.vm.usable_port_range = attr['port'] + 10..attr['port'] + 100

    end
  end

end
