name: CI

on:
  push:
  schedule:
    - cron: '2 10 28 * *'

jobs:
  tag:
    runs-on: macos-latest
    outputs:
      new_version: ${{ steps.tag.outputs.new_version }}
    steps:
    - uses: actions/checkout@master
      with:
        # Fetches entire history, so we can analyze commits since last tag
        fetch-depth: 0
    - id: tag
      name: Bump version and push tag
      uses: mathieudutour/github-tag-action@v4.6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [win7-ie8, win7-ie9, win7-ie10, win7-ie11, win81-ie11, win10-edge]
    name: ${{ matrix.os }}
    needs: tag
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download
      run: |
        ./download-vm.sh ${{ matrix.os }}
    - name: Build
      env:
        VAGRANT_CLOUD_ACCESS_TOKEN: ${{ secrets.VAGRANT_CLOUD_ACCESS_TOKEN }}
      run: |
        ./download-prerequisites.sh
        ./automated-win.sh ${{ matrix.os }} ${{ needs.tag.outputs.new_version }}
    - uses: actions/upload-artifact@v1
      if: ${{ always() }}
      with:
        name: recordings from ${{ matrix.os }} build for ${{ github.sha }}
        path: recordings
  no-additions:
    strategy:
      fail-fast: false
      matrix:
        os: [win7-ie8, win7-ie9, win7-ie10, win7-ie11, win81-ie11, win10-edge]
    name: ${{ matrix.os }}-no-additions
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download
      run: |
        ./download-vm.sh ${{ matrix.os }}
    - name: Build
      run: |
        ./download-prerequisites.sh
        ./automated-win.sh ${{ matrix.os }} manual
    - uses: actions/upload-artifact@v1
      if: ${{ always() }}
      with:
        name: recordings from ${{ matrix.os }}-no-additions build for ${{ github.sha }}
        path: recordings
