name: CI

on:
  push:
  schedule:
    - cron: '2 10 28 * *'

env:
  VB_RECORDING: "on"

jobs:
  win7-ie8:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download
      working-directory: ./vms
      run: |
        ./download-vm.sh win7-ie8
    - name: Build
      run: |
        ./download-prerequisites.sh
        ./automated-win.sh win7-ie8 || true
    - uses: actions/upload-artifact@v1
      with:
        name: recording from ${{github.job}} build
        path: "*.webm"
  win7-ie9:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download
      working-directory: ./vms
      run: |
        ./download-vm.sh win7-ie9
    - name: Build
      run: |
        ./download-prerequisites.sh
        ./automated-win.sh win7-ie9 || true
    - uses: actions/upload-artifact@v1
      with:
        name: recording from ${{github.job}} build
        path: "*.webm"
  win7-ie10:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download
      working-directory: ./vms
      run: |
        ./download-vm.sh win7-ie10
    - name: Build
      run: |
        ./download-prerequisites.sh
        ./automated-win.sh win7-ie10 || true
    - uses: actions/upload-artifact@v1
      with:
        name: recording from ${{github.job}} build
        path: "*.webm"
  win7-ie11:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download
      working-directory: ./vms
      run: |
        ./download-vm.sh win7-ie11
    - name: Build
      run: |
        ./download-prerequisites.sh
        ./automated-win.sh win7-ie11 || true
    - uses: actions/upload-artifact@v1
      with:
        name: recording from ${{github.job}} build
        path: "*.webm"
  win81-ie11:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download
      working-directory: ./vms
      run: |
        ./download-vm.sh win81-ie11
    - name: Build
      run: |
        ./download-prerequisites.sh
        ./automated-win.sh win81-ie11 || true
    - uses: actions/upload-artifact@v1
      with:
        name: recording from ${{github.job}} build
        path: "*.webm"
  win10-edge:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download
      working-directory: ./vms
      run: |
        ./download-vm.sh win10-edge
    - name: Build
      run: |
        ./download-prerequisites.sh
        ./automated-win.sh win10-edge || true
    - uses: actions/upload-artifact@v1
      with:
        name: recording from ${{github.job}} build
        path: "*.webm"
