name: CI

on:
  push:
    branches-ignore:
      - master
  schedule:
    - cron: '2 10 28 * *'

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [win7-ie8, win7-ie9, win7-ie10, win7-ie11, win81-ie11, win10-edge]
    name: ${{ matrix.os }}
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Dependencies
      run: |
        brew install bash curl-openssl
        echo "/usr/local/opt/curl-openssl/bin" >> $GITHUB_PATH
    - name: Build
      run: |
        ./automated-win.sh ${{ matrix.os }} || \
          ./automated-win.sh ${{ matrix.os }}
    - uses: actions/upload-artifact@v1
      if: ${{ always() }}
      with:
        name: recordings from ${{ matrix.os }} build for ${{ github.sha }}
        path: recordings
