name: Main

on:
  push:
  schedule:
    - cron: '16 19 2 * *'

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.tag.outputs.version }}
    steps:
    - uses: actions/checkout@v2.4.0
    - id: tag
      if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
      run: ./release.sh
  release:
    strategy:
      fail-fast: false
      matrix:
        os: [win7-ie8, win7-ie9, win7-ie10, win7-ie11, win81-ie11, win10-edge]
        mode: [auto, manual]
    name: ${{ matrix.os }} ${{ matrix.mode }}
    needs: tag
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Dependencies
      run: |
        brew install bash curl-openssl
        echo "/usr/local/opt/curl-openssl/bin" >> $GITHUB_PATH
        gem install http
    - name: Build
      run: |
        ./automated-win.sh ${{ matrix.os }} ${{ matrix.mode }} || \
          ./automated-win.sh ${{ matrix.os }} ${{ matrix.mode }} || \
          ./automated-win.sh ${{ matrix.os }} ${{ matrix.mode }}
    - name: Release
      if: ${{ matrix.mode == 'auto' }}
      env:
        VAGRANT_CLOUD_ACCESS_TOKEN: ${{ secrets.VAGRANT_CLOUD_ACCESS_TOKEN }}
        X_MIE_VERSION: ${{ needs.tag.outputs.new_version }}
      run: |
        ./automated-win.sh ${{ matrix.os }} ${{ matrix.mode }} || \
          ./automated-win.sh ${{ matrix.os }} ${{ matrix.mode }} || \
          ./automated-win.sh ${{ matrix.os }} ${{ matrix.mode }}
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: recordings from ${{ matrix.os }} ${{ matrix.mode }} build for ${{ github.sha }}
        path: recordings
    - if: ${{ always() }}
      run: rm -f "${{ matrix.os }}.box"
