name: Release

on:
  push:
    branches:
      - master

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.tag.outputs.new_version }}
    steps:
    - uses: actions/checkout@master
      with:
        # Fetches entire history, so we can analyze commits since last tag
        fetch-depth: 0
    - id: tag
      name: Bump version and push tag
      uses: mathieudutour/github-tag-action@v4.6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
  release:
    strategy:
      fail-fast: false
      matrix:
        os: [win7-ie8, win7-ie9, win7-ie10, win7-ie11, win81-ie11, win10-edge]
    name: ${{ matrix.os }}
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Dependencies
      run: |
        brew install bash
    - name: Download
      run: |
        ./download-vm.sh ${{ matrix.os }}
    - name: Build
      env:
        VAGRANT_CLOUD_ACCESS_TOKEN: ${{ secrets.VAGRANT_CLOUD_ACCESS_TOKEN }}
        VERSION: ${{ github.event.release.tag_name }}
      run: |
        ./download-prerequisites.sh ${{ matrix.os }}
        ./automated-win.sh ${{ matrix.os }}
    - uses: actions/upload-artifact@v1
      if: ${{ always() }}
      with:
        name: recordings from ${{ matrix.os }} build for ${{ github.sha }}
        path: recordings
