name: Release

on:
  push:
    branches:
      - master
  schedule:
    - cron: '25 7 2 * *'

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.tag.outputs.version }}
    steps:
    - uses: actions/checkout@v2.3.4
    - id: tag
      uses: wendbv/calver-tag-action@v1.0.1
  release:
    strategy:
      fail-fast: false
      matrix:
        os: [win7-ie8, win7-ie9, win7-ie10, win7-ie11, win81-ie11, win10-edge]
    name: ${{ matrix.os }}
    needs: tag
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Dependencies
      run: |
        brew install bash curl-openssl
        echo "/usr/local/opt/curl-openssl/bin" >> $GITHUB_PATH
    - name: Build
      env:
        VAGRANT_CLOUD_ACCESS_TOKEN: ${{ secrets.VAGRANT_CLOUD_ACCESS_TOKEN }}
        X_MIE_VERSION: ${{ needs.tag.outputs.new_version }}
      run: |
        ./automated-win.sh ${{ matrix.os }} || \
          ./automated-win.sh ${{ matrix.os }}
    - uses: actions/upload-artifact@v1
      if: ${{ always() }}
      with:
        name: recordings from ${{ matrix.os }} build for ${{ github.sha }}
        path: recordings
